# Blueprint: Price-based Switch Control
# Description: Control switches based on NordPool sensor prices.
# Source: https://your-source-url.com

blueprint:
  name: Price-based Switch Control
  description: Control switches based on NordPool sensor prices.
  domain: automation

input:
  price_entity:
    name: NordPool sensor
    selector:
      entity:
        device_class: monetary
  switch:
    name: Lülitid
    selector:
      entity:
        domain: switch
        multiple: true
  max_price:
    name: Maksimaalne hind
    description: Maksimaalne hind, millest madalamal lülitatakse sisse
    default: 5.0

trigger:
  platform: time_pattern
  minutes: 0
  seconds: 15

action:
  service: >
    {% if states(input.price_entity) | float <= input.max_price %}
      switch.turn_on
    {% else %}
      switch.turn_off
    {% endif %}
  target:
    entity_id: input.switch
