blueprint:
  name: Price-based Switch Control
  description: Control switches based on NordPool sensor prices.

input:
  price_entity:
    name: NordPool sensor
    selector:
      entity:
        device_class: monetary
  switch:
    name: Lülitid
    selector:
      entity:
        domain: switch
        multiple: true
  max_price:
    name: Maksimaalne hind
    description: Maksimaalne hind, millest madalamal lülitatakse sisse
    default: 5.0 # Muuda vastavalt soovile

variables:
  _price: !input price_entity
  price_now: "{{ states(_price) | float }}"
  price_avg: "{{ state_attr(_price, 'average') | float }}"
  max_price: !input max_price

trigger:
  - platform: time_pattern
    minutes: 0
    seconds: 15 # väike viivitus täistunnist

action:
  - service: >
      {% if price_now <= price_avg and price_now <= max_price %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    alias: "Hind on alla keskmise ja maksimaalse, lülitan lülitid ümber"
    target:
      entity_id: !input switch
